import type { AppContext, Room, User } from '../types';
import type { MembershipApplication } from '../db/membership';
import type { MembershipConfig } from '../lib/membership-config';
import { esc } from './layout-utils';
const t=(ctx:AppContext,en:string,he:string)=>ctx.locale==='he'?he:en;
const csrf=(ctx:AppContext)=>`<input type="hidden" name="csrf" value="${esc(ctx.csrfToken ?? '')}">`;
export function renderMembership(ctx:AppContext,config:MembershipConfig,app:MembershipApplication|null,room:Room|null,staff:User|null,history:{status:string;reason:string;created_at:string}[]):string {
  const status=ctx.user?.intake_status ?? 'none';
  const mayApply=config.enabled && ['applicant','declined'].includes(status);
  const statusText=!config.enabled?t(ctx,'Membership restrictions are suspended. You can participate according to your room permissions. Your application history is retained.','מגבלות החברות מושהות. אפשר להשתתף בהתאם להרשאות החדרים. היסטוריית הבקשות נשמרת.'):status==='pending'?t(ctx,'Your application is awaiting staff review. You can read permitted rooms and contact staff while you wait.','הבקשה ממתינה לבדיקת הצוות. אפשר לקרוא בחדרים המותרים וליצור קשר עם הצוות.'):
    status==='declined'?t(ctx,'Your application was declined. Read the reason below; you can submit a new application or contact staff.','הבקשה נדחתה. אפשר לקרוא את הסיבה למטה, להגיש בקשה חדשה או ליצור קשר עם הצוות.'):
    status==='approved'?t(ctx,'You are a Trusted member. Welcome! You may remove your introduction below.','הבקשה אושרה. ברוכים הבאים! אפשר להסיר את ההיכרות למטה.'):
    status==='applicant'?t(ctx,'Introduce yourself or apply privately. Participation outside the application room awaits approval.','אפשר להציג את עצמך או לפנות באופן פרטי. ההשתתפות בשאר החדרים ממתינה לאישור.'):
    t(ctx,'Your account has community access. No membership application is required.','לחשבון שלך יש גישה לקהילה. אין צורך בבקשת חברות.');
  return `<section class="card" aria-labelledby="membership-title"><h1 id="membership-title">${t(ctx,'Membership status','מצב החברות')}</h1>
    ${!config.enabled?`<p>${t(ctx,'Membership review is currently disabled. Existing applications and decisions are retained.','בדיקת החברות מושבתת כעת. בקשות והחלטות קיימות נשמרות.')}</p>`:''}
    <p>${statusText}</p>${app?.decision_reason?`<p>${esc(app.decision_reason)}</p>`:''}
    ${staff?`<p><a href="/dms/${encodeURIComponent(staff.display_name ?? '')}">${t(ctx,'Contact staff privately','יצירת קשר פרטי עם הצוות')}: ${esc(staff.display_name ?? '')}</a></p>`:''}
    ${mayApply&&room?`<p><a href="/r/${encodeURIComponent(room.slug)}">${t(ctx,'Write an introduction in','כתיבת היכרות בחדר')} ${esc(room.name)}</a></p>`:''}
    ${mayApply?`<form method="post" action="/membership/apply">${csrf(ctx)}<label for="application-text">${t(ctx,'Private application (only staff can read this)','בקשה פרטית (רק הצוות יכול לקרוא)')}</label><textarea id="application-text" name="application_text" required maxlength="10000" rows="6"></textarea><button type="submit" class="btn">${t(ctx,'Submit application','שליחת בקשה')}</button></form>`:''}
    ${app?.status==='approved'&&app.introduction_topic_id?`<form method="post" action="/membership/introduction/remove">${csrf(ctx)}<p>${t(ctx,'Removal hides your linked introduction and its replies from normal browsing.','ההסרה מסתירה את ההיכרות המקושרת ואת התגובות לה מהגלישה הרגילה.')}</p><button type="submit" class="btn">${t(ctx,'Remove my introduction','הסרת ההיכרות שלי')}</button></form>`:''}
    ${history.length?`<h2>${t(ctx,'Decision history','היסטוריית החלטות')}</h2><ul>${history.map(d=>`<li>${esc(d.created_at)} — ${esc(d.status==='approved'?t(ctx,'Approved','אושרה'):d.status==='declined'?t(ctx,'Declined','נדחתה'):d.status)} ${esc(d.reason)}</li>`).join('')}</ul>`:''}</section>`;
}
export function renderIntake(ctx:AppContext,apps:MembershipApplication[],config:MembershipConfig,pageNumber=0):string {
 return `<section><h1>${t(ctx,'Membership applications','בקשות חברות')}</h1>${ctx.user?.access_level==='admin'?`<p><a href="/admin/membership-settings">${t(ctx,'Membership settings','הגדרות חברות')}</a></p>`:''}
 ${ctx.user?.access_level==='admin'&&config.remindersEnabled?`<form method="post" action="/admin/intake/reminders">${csrf(ctx)}<button class="btn">${t(ctx,'Send reminders to applicants without submissions (3+ days)','שליחת תזכורות למועמדים שלא הגישו בקשה (3 ימים ומעלה)')}</button></form>`:''}
 ${apps.length?apps.map(a=>`<article class="card"><h2>${esc(a.display_name ?? '')} — ${esc(a.status === 'pending' ? t(ctx,'Pending','ממתינה') : a.status === 'approved' ? t(ctx,'Approved','אושרה') : t(ctx,'Declined','נדחתה'))}</h2><p>${esc(a.created_at)}</p><p style="white-space:pre-wrap">${esc(a.application_text)}</p>
 ${a.introduction_short_id?`<a href="/t/${encodeURIComponent(a.introduction_short_id)}">${t(ctx,'View introduction','צפייה בהיכרות')}</a>`:''}
 <p>${t(ctx,'Public decision reason','סיבת החלטה ציבורית')}: ${esc(a.decision_reason)}</p>${a.decided_at?`<p>${t(ctx,'Decision by / time','החלטה של / זמן')}: ${esc(a.decision_actor ?? '—')} / ${esc(a.decided_at)}</p><p>${t(ctx,'Decision notes (historical)','הערות החלטה (היסטוריות)')}: ${esc(a.decision_notes ?? '')}</p>`:''}
 <form method="post" action="/admin/intake/${a.id}/notes">${csrf(ctx)}<label for="notes-${a.id}">${t(ctx,'Private staff notes','הערות צוות פרטיות')}</label><textarea id="notes-${a.id}" name="staff_notes" maxlength="10000">${esc(a.staff_notes)}</textarea><button class="btn">${t(ctx,'Save notes','שמירת הערות')}</button></form>
 ${a.status==='pending'?`<form method="post" action="/admin/intake/${a.id}/decision">${csrf(ctx)}<label for="reason-${a.id}">${t(ctx,'Reason shown to applicant','סיבה שתוצג למועמד')}</label><textarea id="reason-${a.id}" name="decision_reason" maxlength="2000"></textarea><label for="decision-notes-${a.id}">${t(ctx,'Private decision notes','הערות החלטה פרטיות')}</label><textarea id="decision-notes-${a.id}" name="staff_notes" maxlength="10000">${esc(a.staff_notes)}</textarea><button class="btn" name="decision" value="approved">${t(ctx,'Approve','אישור')}</button> <button class="btn" name="decision" value="declined">${t(ctx,'Decline','דחייה')}</button></form>`:''}</article>`).join(''):`<p>${t(ctx,'No applications yet.','אין בקשות עדיין.')}</p>`}<nav aria-label="${t(ctx,'Application pages','עמודי בקשות')}">${pageNumber>0?`<a href="/admin/intake?page=${pageNumber-1}">${t(ctx,'Previous','הקודם')}</a>`:''} ${apps.length===100?`<a href="/admin/intake?page=${pageNumber+1}">${t(ctx,'Next','הבא')}</a>`:''}</nav></section>`;
}
